### PR TITLE
Dropping Sort Bar

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're reverting PR #831 and dropping the Sort Bar, instead.

cc @eshurakov (Thank youuu!!)
Ref. #626 

### Test
- [ ] Verify there is no Sort Bar visible anymore
- [ ] Verify the Note List area's top insets match the Tag List area

### Release
These changes do not require release notes.

### CODE REVIEW

**Review by eshurakov — APPROVED** [review]
Looks good! :shipit:

**Comment by jleandroperez** [comment]
Thank you @eshurakov !! (I forgot to delete the `SortBarView` class!!).

**Comment by jleandroperez** [comment]
Thank you Evgeny!!

**Comment by pachlava** [comment]
[testing] fix/feature verified on MBP 16" Intel | macOS 11.2 | Simplenote 2.8 beta3 (11220)

**Pull request merged**
