### PR TITLE
Updates release notes

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
In this PR we're dropping RTL references from the release notes, since the app doesn't support Persian localizations (yet, that's our next project!)

@aerych May I bug you with a really really super quick one?
Thanks in advance!!

### Test
- [x] Verify the CI is green!

### CODE REVIEW

**Comment by jleandroperez** [comment]
Thank you Eric!!

**Comment by jleandroperez** [comment]
/cc @mokagio Sir!! no need for a new build, but we could use new Release strings!

Thank you!!

**Comment by mokagio** [comment]
>  but we could use new Release strings!

That's ok, I think. We send the info to App Store Connect only when we wrap up the release, so no harm done. I'll see if I can update App Center and TestFlight now.

**Comment by jleandroperez** [comment]
Thank you Gio!!!

**Pull request merged**
