### PR TITLE
Notes List: Separators

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're wiring Table Row separators.

@eshurakov May I bug you yet again sir?
Thank yoouu!!

Ref. #718

### Test
1. Log into your account

- [x] Verify the Notes List rows display a bottom separator
- [x] Verify the new separators look great in Light / Dark mode
- [x] Verify that selected rows (in the Notes List) don't display separators

### Release
`RELEASE-NOTES.txt` was updated in 983afeb with:

> Notes List now display row separators #758

### Screenshots

Light|Dark
-|-
Screen Shot 2020-12-15 at 2 13 53 PM|Screen Shot 2020-12-15 at 2 14 07 PM

### CODE REVIEW

**Comment by eshurakov** [comment]
Hey @jleandroperez, here is what I found on Catalina:
1. There is a strange super white top separator
Screenshot 2020-12-15 at 20 23 02

2. Separators left aligned to the second letter :-)
3. When I select a cell, there is top separator visible
4. If I click on each cell from top to bottom, separators are totally gone

Screenshot 2020-12-15 at 20 23 42
Screenshot 2020-12-15 at 20 27 59

**Comment by jleandroperez** [comment]
@eshurakov all comments addressed, should be good now. Ready for another peek!!

Thanks in advance!!

**Review by eshurakov — APPROVED** [review]
Beautiful!

:shipit:

**Comment by jleandroperez** [comment]
Thank you sir!!

**Comment by jleandroperez** [comment]
Merging this one. Thanks again Evgeny!!

**Pull request merged**
