### PR TITLE
Email Verification: Preventing UI Resize

### LINKED ISSUE #821: [Email Verification] 'Review your account' and 'Verify your Email' screens are too resizeable
### Expected
Should not be resizeable at all, or resizing should be wisely limited.

### Observed
Possible to resize the window a lot.

### Reproduced
1. Log in as a user with not verified email
2. See the new 'Review your account' / 'Verify your Email' screens
3. Both screens can be resized quite a bit

https://user-images.githubusercontent.com/73365754/106038557-c50f7f00-60e0-11eb-9a31-0cf88b04ee08.mov

Make|Model|macOS Version|App Version
-|-|-|-
Mac|MBP 16|11.1|2.7

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're enforcing a minimum height for the Account Verification UI.

cc @eshurakov 
Closes #821

### Test
1. Log in as a user with not verified email
2. See the new 'Review your account' / 'Verify your Email' screens

- [ ] Verify the Emal Verification UI **can not** be resized!

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by eshurakov** [comment]
@jleandroperez I checked PR on Catalina and I can change width of Account Verification sheet.

**Comment by jleandroperez** [comment]
@eshurakov Ready for another look!

**Comment by jleandroperez** [comment]
(Thank you!!)

**Review by eshurakov — APPROVED** [review]
Works great!

:shipit:

**Comment by jleandroperez** [comment]
Thank you sir!!

**Comment by jleandroperez** [comment]
cc @mokagio (OR) @loremattei gentleman, would it be possible to get a new Beta binary?

Thanks in advance!!

**Comment by mokagio** [comment]
@jleandroperez we're almost done with the Apple Silicon support (#802, #803). Would it be okay to ship a new beta when those changes are in, too?

**Comment by jleandroperez** [comment]
@mokagio Of course sir! thanks a lot!!

**Pull request merged**
