### PR TITLE
Tracks: Opt Out

### LINKED ISSUE #238: Tracks: Opt Out
### Details:
- [ ] Add a new boolean field to the`Settings` entity (Simperium backed) to persist if the user opted out from Tracks
- [ ] Add a new Switch in the Settings UI

Ref. [iOS Issue](https://github.com/Automattic/simplenote-ios/issues/222)

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR implements Tracks Opt Out, via Simperium Sync, and a super simple Privacy UI (based on the About UI).

@roundhill i'd be more than happy to twean the Privacy UI, as needed. Screenshots below (Dark / Light mode in Mojave).

Thanks in advance!!!

Closes #238

### Scenario: Sync'ing
1. Launch the latest iOS Version (with the Privacy Settings)
2. Launch Simplenote macOS and open the Privacy Settings
3. Toggle iOS's Privacy settings
4. Verify macOS nearly instantaneously refreshes, and displays the new setting

### Scenario: Learn More
1. Launch Simplenote Mac
2. Open the Privacy Settings
3. Click over the `Help us improve (...)` Label (or right image)
4. Verify Safari shows up with our Privacy Policy

### Scenario: Opt Out
1. Check out this commit: [2aa1b8e](
https://github.com/Automattic/simplenote-macos/pull/242/commits/2aa1b8e574e7ae2bb56c5ef0fca4b663b2e75ca5)
2. Enable the Tracks Opt Out
3. Trigger anything that might result in an event (ie. open a note)
4. Verify the following shows up in the console: `## Disregarding Event (...)`
5. Enable Tracks
6. Trigger something that might result in an event (ie. open a note)
7. Verify the following shows up in the console: `## Sending Event (...)`

---

screen shot 2018-09-25 at 11 25 15 am

screen shot 2018-09-25 at 11 25 35 am

### CODE REVIEW

**Comment by roundhill** [comment]
screen shot 2018-09-25 at 10 26 45 am

screen shot 2018-09-25 at 10 27 13 am


How about `Privacy Settings` for both of those labels? (we link to the privacy policy from the About menu)

**Comment by roundhill** [comment]
Can we squeeze in the `Learn more` text in the summary, underlined if possible?

**Comment by roundhill** [comment]
screen shot 2018-09-25 at 10 36 37 am

The text and checkbox are _slightly_ off-center vertically, needs to be bumped up a pixel or two.

**Comment by roundhill** [comment]
Working great, just a few cosmetic changes and we can :shipit:

**Comment by roundhill** [comment]
Really close, can you just rename `Privacy Policy` to `Privacy Settings` in the menu and header label of the view?

**Comment by jleandroperez** [comment]
Thank you Dan!!!

**Pull request merged**
