### PR TITLE
About: Adds Get Help row

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
In this PR we're adding a new `Get Help` row!

@guarani Sir!! can I trouble you with this one?
cc @SylvesterWilmott for UI reasons!!

### Test
1. Launch Simplenote
2. Open the **About Window**

- [ ] Verify the mouse switches to a pointing cursor as you hover the different entries
- [ ] Verify every clickable item opens a Web onClick

### Release
`RELEASE-NOTES.txt` was updated in 0418542 with:

> New `Get Help` action in Simplenote's About window

### Screenshots
About

### CODE REVIEW

**Review by SylvesterWilmott — APPROVED** [review]
Looks good!

**Comment by jleandroperez** [comment]
Thank you @SylvesterWilmott !!

**Review by guarani — APPROVED** [review]
Apologies for the delay! LGTM!

**Comment by jleandroperez** [comment]
Thanks a lot Paul!!

**Pull request merged**
