### PR TITLE
Simperium: Sync'ing Account Entity

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details
- Updates Simperium to 1.4
- Enables Sync'ing of the Account bucket, backed by **SPJSONStorage**
- Implements the **EmailVerification** entity

@eshurakov May I trouble you with this one?
Thanks in advance!

Ref #800

---

### Test: Unverified Account
0. **Update your mobile-secrets first please!**
1. Checkout commit 181efb6e13a22597c7854872d01cbaec37fb28ad (contains debug code!)
2. Log into an unverified account

- [x] Verify that the legend `Email Verification` is never printed in your console

### Test: Verified Account
0. **Update your mobile-secrets first please!**
1. Checkout commit 181efb6e13a22597c7854872d01cbaec37fb28ad (contains debug code!)
2. Log into an verified account

- [x] Verify that the legend `Email Verification` does get printed in your console

### Test: Logout
1. Log into an account that has the `email-verification` entity
2. Logout

- [x] Verify the `email-verification` entity is nuked after logout

### Release
These changes do not require release notes.

### CODE REVIEW

**Review by eshurakov — APPROVED** [review]
Looks good!

While testing I found something strange (possible also exist on iOS):
* log in to an account that has `email-verification` entity
* log out, don't kill the app
* log in to an account that doesn't have `email-verification`
* see that `email-verification` entity from the first account is printed in the console

Did we forget to clear json storage when we log out? 🤔

**Comment by jleandroperez** [comment]
- Simperium updated to Mk 1.3: JSONStorage is now neutralized on logout
- EmailVerification entity has been updated to match the latest backend specs

@eshurakov May I bug you with another look on this one?
Thanks in advance!!

**Comment by jleandroperez** [comment]
@eshurakov latest parser (version 4? 5?) ready for review! thank you!!

**Review by eshurakov — APPROVED** [review]
Looks great, thank you!

:shipit:

**Comment by jleandroperez** [comment]
Thank you Evgeny!!

**Pull request merged**
