### PR TITLE
Stronger Passwords 🔥

### LINKED ISSUE #528: Hardened Password Policy
### Details:
We'll update our Password Policy across all the apps.

[iOS Sibling Here](https://github.com/Automattic/simplenote-ios/issues/745)

### Password Criteria:
- Minimum Length: 8 Characters
- Disallowed characters: **[ newline, tab]**
- Must not match the username! 

#### Flow: Signup
Every single new user should meet the new Password criteria.

#### Flow: Login 
0. Login Password validation (in the initial stage) should remain the same
1. Successful login event
2. Simplenote we'll verify if the password meets the new hardened criteria
2.A. When that's not the case, we'll display an alert explaining what's going on
2.A.1. After accepting the alert, we'll open the new Password Reset UI
2.B. Otherwise Auth proceeds as usual

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
In this PR we're wiring the latest Simperium branch, which includes a new workflow that prompts users to upgrade their passwords.

- 8 Characters Minimum
- Passwords cannot match the Email
- Passwords must not contain `newline` / `tab` characters

Includes Simperium [PR 591](https://github.com/Simperium/simperium-ios/pull/591) + [PR 590](https://github.com/Simperium/simperium-ios/pull/590)

Closes #528 

@aerych Sir!! May I bother you with this one?
**Thanks in advance!!!**

### Testing: Interface
1. Launch Simplenote
2. Make sure you're logged out!

- [x] Verify the Authentication UI no longer has round corners
- [x] Verify that the Auth fields don't have round corners either

### Testing: Signup
1. Launch Simplenote
2. Click over Sign Up

- [x] Verify that invalid emails are rejected
- [x] Verify that non matching passwords are rejected
- [x] Verify that passwords shorter than 8 characters are rejected
- [x] Verify that a valid password is allowed!
- [x] Verify that during a SignUp (BG) call the spinner shows up (and the interface is locked)

### Testing: Login + Strong Passwords
0. DM me for a testing account!
1. Launch Simplenote

- [x] Verify that an account with a strong password is authenticated
- [x] Verify that during a LogIn (BG) call the spinner shows up (and the interface is locked)

### Testing: Login + Reset Password
0. DM me for a testing account!
1. Launch Simplenote

- [x] Verify that an insecure password triggers the `PW Reset Required` alert
- [x] Verify that pressing `Cancel` dismisses the alert
- [x] Verify that pressing `Reset` (in the PR reset Alert) opens the Reset PW web, with your email prefilled
- [x] Verify that after the Password is successfully reset, Simplenote is brought up to the foreground again

### Release
`RELEASE-NOTES.txt` was updated in 8b3e6e8 with:

> Updated Password Strength requirements.

---

### Screenshots
Reset Alert

### CODE REVIEW

**Comment by aerych** [comment]
>  Verify that during a SignUp (BG) call the spinner shows up (and the interface is locked 

I tested this by turning on the network link conditioner and setting it to Very Bad Network. This gave me enough time to look over the UI and to tap around a bit.  I never saw a spinner and I was able to tap around the UI, switch from the sign up form to the login form, and tap on the forgot password button to launch the forgot password page in a browser.

**Comment by aerych** [comment]
> Verify that after the Password is successfully reset, Simplenote is brought up to the foreground again

This was a little fiddly as I was using the test account.  What I did was, in the web form, I replaced the test account's email addresss with my own account's email address and used that.  Then when I received the email I clicked the link, entered a new password, and then was prompted to open the app store version of Simplenote.  Seems good with that caveat :)

**Comment by jleandroperez** [comment]
✅  Fixed: SignUp Spinner
✅  Fixed: Properly locking the whole UI during a SignUp

Thank you Eric!!! All the things are good now!!

**Comment by aerych** [comment]
I made one last pass and retested each scenario.  Everything looks great now.  :shipit: !!

**Comment by jleandroperez** [comment]
Thank you Eric!!!

**Pull request merged**
