### PR TITLE
Tags List: Adjusting Separator

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're adjusting the Header Separator in the Tags List Area. 
This was spotted by @eshurakov in #833.

cc @SylvesterWilmott 
cc @eshurakov 

Thank you gentleman!!

### Test
1. Log into your account
2. Scroll over the Tags List so that the Header separator shows up

- [ ] Verify the Tags separator looks super in Light Mode
- [ ] Verify the Tags separator looks super in Dark Mode as well!

### Release
These changes do not require release notes.

### Screenshots
New Dark|New Light
-|-
Screen Shot 2021-02-08 at 4 38 38 PM|Screen Shot 2021-02-08 at 4 38 58 PM

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
From the screenshot, it looks like the dark mode tag list separator changed to being light. This should remain black, this change should only affect the light mode.

**Comment by jleandroperez** [comment]
Back, in black!

Thank you @SylvesterWilmott !! @eshurakov ready for another looks sir (thank you!!)

**Comment by SylvesterWilmott** [comment]
Thanks @jleandroperez

**Review by eshurakov — APPROVED** [review]
Looks good! :shipit:

**Comment by jleandroperez** [comment]
Thank you gentleman!!

**Comment by pachlava** [comment]
[testing] fix/feature verified on MBP 16" Intel | macOS 11.2 | Simplenote 2.8 beta3 (11220)

**Pull request merged**
