### PR TITLE
Don’t use global CocoaPods

### PR DESCRIPTION
**Pull request by jkmassel**
We're trying to get away from global CocoaPods installations for our iOS (and macOS!) projects in order to ensure tooling consistency – this applies that policy to this project.

It just requires a `bundle exec` in front of `pod` commands. :) 

(see: https://github.com/Automattic/Automattic-Tracks-iOS/pull/85)

### CODE REVIEW

**Comment by roundhill** [comment]
Sounds good. Should we update the `README`? Do you just run `bundle install` then `bundle exec pod install`?

**Comment by jkmassel** [comment]
That's right! I'll adjust this PR to update the `README` as well, thanks! :)

**Comment by jkmassel** [comment]
Added! If you're good with it @roundhill, I think this is ready to merge!

**Comment by roundhill** [comment]
Looks good! Should we apply the same to simplenote-ios?

**Pull request merged**
