### PR TITLE
Authentication: Displaying Titlebar's Close Button

### LINKED ISSUE #658: Adjust Authentication
### Details:
- Add the window's semaphore to minimize / close the authentication window

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're adjusting the Authentication Window, so that the standard buttons are displayed. Note that only Close is allowed

cc @aerych Sir, you game for a quick PR?
Thanks in advance!

Closes #658

### Test
- [x] Verify that the Login Window now displays the close button (top left corner)
- [x] Verify that clicking over the Close button effectively dismisses the Login Window
- [x] Verify that (when not authenticated) clicking over the Simplenote (Dock) Icon reopens the Authentication window
- [x] Verify that (when authenticated) clicking over the Simplenote (Dock) Icon reopens the main window

### Release
These changes do not require release notes.

### Screenshot
Screen Shot 2020-08-25 at 20 03 16

### CODE REVIEW

**Review by mokagio — COMMENTED** [review]
I'm not seeing the title bar buttons in the authentication window.

simplenote-macos-no-title-bar

I tried the App Store scheme too.

**Review by mokagio — COMMENTED** [review]
I tried 2367bdebcca2d8196831d30451e787828d904390, but I still can't see the buttons. 

image

**Comment by aerych** [comment]
@mokagio I'm wondering if maybe there could be something stale in the build folder that's getting picked up? Is this still happening after a clean > build?  I'm seeing the buttons when I test on macOS 10.15.5 (19F101).   
Are you running a different version of macOS?

**Comment by jleandroperez** [comment]
Thank you @aerych !!!

@mokagio just to rule out CocoaPods caching issues (there was a problem with Simperium 0.8.29 release, I had to hotfix it!), I ended up bumping up to 0.8.30.

Should be good now Gio, mind taking another look? (It's really gotta work fine on your mac, otherwise the next binary is gonna get rejected!)

**Comment by jleandroperez** [comment]
Merging this one **just in case** it gets lost behind. This addresses a Mac AppStore rejection.

Thanks everyone!!

**Comment by mokagio** [comment]
Catching up on this, sorry for the radio silence, I was AFK.

I didn't think about clearing my `DerivedData`, although it sounds obvious in hindsight given this was a UI issue.

Works now:

image

**Comment by jleandroperez** [comment]
Thank you @mokagio !! Good to cut `release/2.1` anytime, I'll bump up the pending issues / PRs in the milestone.

Thanks everyone!!

**Pull request merged**
