### PR TITLE
Window: Preventing zoom when double clicking the First Responder

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're adjusting the Window's behavior, so that double clicking over the First Responder doesn't Zoom into the Window.

cc @eshurakov This one annoyed me for a while!!
Ref. #626 

### Test
1. Click over the Search Bar
2. Enter any random term
3. Double click over the Search Bar

- [ ] Verify the Window doesn't expand
- [ ] Verify the Search Keyword gets highlighted

### Release
`RELEASE-NOTES.txt` was updated in d49541530f44db14d259fde04cdac0d9304def62 with:

> Fixed a bug that Zoomed the window when double clicking on the Search Bar #841

### CODE REVIEW

**Comment by eshurakov** [comment]
It works, but: when search bar is first responder it is now not possible to zoom if you double tap on toolbar area above the editor

**Comment by jleandroperez** [comment]
@eshurakov should be super solid now sir!! ready for another look!

**Thank you!!**

**Review by eshurakov — APPROVED** [review]
Works great! :shipit:

**Comment by jleandroperez** [comment]
Thank you sir!!

**Comment by pachlava** [comment]
[testing] fix/feature verified on MBP 16" Intel | macOS 11.2 | Simplenote 2.8 beta3 (11220)

**Pull request merged**
