### PR TITLE
Magic Links: The one PR to rule them all

### LINKED ISSUE #1187: Magic Links: Switch to Code Authentication
### Details:
- [x] Implement macOS Navigation Controller #1193
- [x] Polish NagitationController Animations #1196
- [x] Refactor AuthUI to handle State and Mode Definitions #1195
- [x] Implement a new Code and Password Interfaces #1197
- [x] Ensure if you get rate limited, during login, you may proceed to the Enter Password UI
- [x] Verify the Magic Link Flow is still supported
- [x] Verify the Invalid Token UI is still triggered https://github.com/Automattic/simplenote-macos/pull/1198
- [x] Adjust UI Details https://github.com/Automattic/simplenote-macos/pull/1198
   - [x] Enter Code TextField should probably be readable (since it's easy to miss, and it expires quickly, anyways)
   - [x] Going Back from the Enter Code UI results in the "Enter Email" UI, with your email highlighted
   - [x] Enter password button's textColor doesn't match the border
   - [x] Enter Password UI needs a header, too, with the account's email (recently added in iOS).
- [x] Update Error Handling: Invalid and Expired Code Errors
- [x] Fix weird back button animation
- [x] Animate Window Resize

### PR DESCRIPTION
**Pull request by charliescheer**
### Fix
... one PR to find them, one PR to bring them all, and in the darkness bind them...

This PR brings together all of the previous changes to magic links authorization that has been made on SNMac and then merges them all back into trunk.  There aren't any unreviewed changes here (although we might make some button copy changes before merging) but we should smoke test the auth views before we merge it back to trunk and then release the new auth to the masses.

fixes: #1187 

### Test
***(Required)*** List the steps to test the behavior.  For example:

Nothing specific here, but we want to test the new auth views so, try and consider this list of things:
1. Load through the different views in the auth process and make sure that going back and forth between views to ensure it looks right and the animations are solid
2. Attempt a sign up
3. Attempt login with code.  While testing code login, try entering bad codes and expired codes
4. Attempt login with email link.  Also test an expired link
5. Attempt login with password
6. Make sure that if you put invalid values in the different text fields that you are given an error

### Review
***(Required)*** Add instructions for reviewers.  For example:
> Only one developer is required to review these changes, but anyone can perform the review.

### Release
***(Required)*** Add a concise statement to `RELEASE-NOTES.txt` if the changes should be included in release notes. Include details about updating the notes in this section. For example:
Doesn't require updates because it is already there

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by roundhill** [comment]
You shall not pass… invalid login attempts!

**Comment by roundhill** [comment]
(Can be in follow-up PR)

There's just a few capitalization issues that don't match the Figma:
* On the code entry screen change the button label from `Log In` to `Log in`
* Same thing on the password entry screen
* On the password entry screen, Change `Forgot your Password?` to `Forgot your password?`
* ... and any others I may have missed :D

**Review by roundhill — APPROVED** [review]
Tested all the steps and it worked great! Noted a few copy changes that can be added later, or here if you want!

GO MAGIC LINKS!

**Review by jleandroperez — APPROVED** [review]
✅ Code Auth works super
✅ Password Auth also works
✅ Signup is also good, just confirmed
✅ Rate Limited Login handled
✅ Invalid Code error, also, handled
✅ Transitions look super smooth, no Layout constraint errors onscreen
✅ Signup validation(s) also look good
✅ First Responder management also looks good, when you go back / forwards

Nice work Charlie!!

:shipit:

**Pull request merged**
