### PR TITLE
MainWindowController: Enabling movableByBackground

### LINKED ISSUE #935: Window: Improve Drag Areas
### Details
At the moment, the main window can only be dragged from a small area from the top of the window.

Let's switch the [movableByWindowBackground](https://developer.apple.com/documentation/appkit/nswindow/1419072-movablebywindowbackground?language=objc) flag!

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're allowing the Main Window to be draggable from the background.

Closes #935

Thank you Evgenyyyyy

### Test
1. Log into your account

- [ ] Verify you can drag the Main Window from literally anywhere that's not a Table / Editor

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by eshurakov** [comment]
I checked on Catalina and it didn't really worked for me. I still have to use the top part of the top bar to drag the window around. 
The only place where I can use the whole top bar to drag the window around is in the tag list sidebar.

**Comment by jleandroperez** [comment]
@eshurakov Okay this was a tricky one. I believe all the things should be okay now, would it be possible to take another look?

Thanks in advance!!

**Review by eshurakov — APPROVED** [review]
Works great!

**Comment by jleandroperez** [comment]
Thank you @eshurakov !!!

**Comment by jleandroperez** [comment]
@mokagio Sir!! would it be possible to get a new macOS Beta?

Thanks in advance!!

**Comment by mokagio** [comment]
@jleandroperez done 🚀

**Pull request merged**
