### PR TITLE
Magic links: Tweaks and updates

### PR DESCRIPTION
**Pull request by charliescheer**
### Fix
Magic link sign in on SNMac is almost there.  After the last few updates we did some testing and have identified a few things that needed to be fixed.  I have fixed many of those things in this PR.  The list of changes fixed here:
-On Invalid Token UI, when you hit the back button the buttons on the onboarding view don't respond
-Enter Code TextField should probably be readable (since it's easy to miss, and it expires quickly, anyways)
-Going Back from the Enter Code UI results in the "Enter Email" UI, with your email highlighted
-Enter password button's textColor doesn't match the border
-Enter Password UI needs a header, too, with the account's email (recently added in iOS).

### Test
####Login Flow####
1. Launch simplenote, click on login, enter a valid simplenote email into the field
2. Confirm that you receive a code in your email.  Type into the code text field and confirm that you can see the code text
3. Confirm that the password button has the correct color (same as it's border)
4. Click on the login with password button.  Confirm there is a header with your email in it
5. Click the back button twice. Confirm that the email is still in the field but the text is not highlighted

####Invalid Code####
1.  In the steps above you never used the login code.  Give that a bit of time to become in valid.  
2. Launch simplenote and then tap on the link.  You should see the invalid code ui
3. Tap on the back button
4. Confirm that on the view that appears you can use the signup and login buttons to get into the auth flow

### Review
***(Required)*** Add instructions for reviewers.  For example:
> Only one developer is required to review these changes, but anyone can perform the review.

### Release
***(Required)*** Add a concise statement to `RELEASE-NOTES.txt` if the changes should be included in release notes. Include details about updating the notes in this section. For example:
> These changes do not require release notes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by jleandroperez — APPROVED** [review]
✅ All test scenarios are green

Nice work!!

:shipit:

**Comment by roundhill** [comment]
To match iOS can we update this to say `Log in with email`? (Only capitalized first word)

Screenshot 2024-07-25 at 4 23 52 PM

**Comment by jleandroperez** [comment]
Love @roundhill  attention to detail, I've stared at that screen all day, and didn't notice 🤦 !!

**Comment by jleandroperez** [comment]
@charliescheer the actual copy from iOS is `Log in with email` (so we should drop the `Instantly` word!)

**Pull request merged**
