### PR TITLE
Skinning Searchbar

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details
In this PR we're fine tunning the Search Bar's UX.

cc @eshurakov (Thanks in advance!!)
Ref. #626

### Test
- [x] Verify the Search Bar gets highlighted when you click on it
- [x] Verify that typing any keyword filters the Notes List, and highlights keywords in the Editor
- [x] Verify that hiding the Tags List causes the Search Field to compress (avoiding the Window's Semaphore)
- [x] Verify the Note Editor / Tags Editor divider is now white (in dark mode).

### Release
`RELEASE-NOTES.txt` was updated in 955822d with:

> SearchBar UI was adjusted #851

### CODE REVIEW

**Review by eshurakov — APPROVED** [review]
Looks good to me. Checked on Catalina.

:shipit:

**Comment by jleandroperez** [comment]
Thank you Evgeny!!

**Comment by jleandroperez** [comment]
@mokagio Gio!! sorry to bug you!! (Promise we're trying not to mess with SN 2.8 anymore!!).

Would it be possible to get a new binary out there?

Plus: we had to update the Release Notes, one of the new components had to be taken out (not sure if we're still on time for GlotPress or the window has closed already!)

**Comment by mokagio** [comment]
Done: #854.

Regarding the release notes... I've never been in the situation where they changed mid release-cycle, so I'm not sure.

I _think_ it should be fine. Our GlotPress automation should notice they changed and upload a new version. I've added reminders to check for that and to also ping the translation team a few days before submission just in case the community doesn't notice this out-of-schedule change 👍

**Comment by jleandroperez** [comment]
Thank you Gio!!

**Comment by pachlava** [comment]
[testing] fix/feature verified on MBP 16" Intel | macOS 11.2 | Simplenote 2.8 beta3 (11220)

**Pull request merged**
