### PR TITLE
Collaboration: Deprecation Notice

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
This PR implements the new deprecation notice for Collaboration.

### Test
1. Log into Simplenote macOS
2. Open any Note
3. Click on the top right `(...)` button
4. Click on Collaborate

- [ ] Verify an Alert shows up, indicating that Collab is being deprecated
- [ ] Verify that clicking on `Learn More` leads you to the Deprecation Notice placeholder URL
- [ ] Verify that clicking on `Dismiss` closes the Alert

### Screenshots

image

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by spencertransier** [comment]
@jleandroperez I'm working on a new release of Simplenote Mac. Did you want this to get included in that release?

**Comment by jleandroperez** [comment]
Hi there @spencertransier !! No, thank you!!

This one is on hold, for the time being. Thanks for checking!!

**Comment by jleandroperez** [comment]
Closing this PR for now!

**Pull request closed without merging**
