### PR TITLE
AccountVerificationController: Case insensitive comparison

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're fixing a bug that caused the Email Verification alert to show up, in verified accounts.

### Test
1. Verify your account
2. Logout from Simplenote
3. Log into your account: shift randomly the case of each letter ( `eMAIl@DomAin.com`)

- [x] Verify the Email Verification UI doesn't show up after auth

### Release
These changes do not require release notes.

### CODE REVIEW

**Review by eshurakov — APPROVED** [review]
Great catch! Thank you!

:shipit:

**Comment by jleandroperez** [comment]
Thank you Evgeny!!

**Comment by jleandroperez** [comment]
@mokagio Sir!! Would it be possible to have another 2.7 build? (Super okay to delay until Apple Silicon is merged!)

**Comment by jleandroperez** [comment]
(Thanks in advance!!)

**Comment by pachlava** [comment]
[testing] fix verified with MBP 16" | Big Sur 11.1 | SN 2.7-beta2

Confirm that issue was reproducible in first beta, and not reproducible in second one.

**Pull request merged**
