### PR TITLE
Merge release 2.8 into trunk

### PR DESCRIPTION
**Pull request by mokagio**
Leaving this as a draft till we actually release it. Still, I'd appreciate a review anyway.

Thanks 🙇‍♂️ .

### CODE REVIEW

**Review by jkmassel — COMMENTED** [review]
Code looks ok but weirdly, a CircleCI job isn't running?

**Comment by mokagio** [comment]
The "Build App Store Target" hasn't reported yet because, despite being required, it's part of `develop` but not of `release/2.8`

See #863.

**Comment by mokagio** [comment]
This has now been published on the Store: Merging it.

**Comment by jleandroperez** [comment]
Thank you Gio!!

**Pull request merged**
