### PR TITLE
Shortcuts: copy note content

### PR DESCRIPTION
**Pull request by charliescheer**
### Fix
So one of the things that would be nice with shortcuts is to be able to get the content out of a note so you can apply it to another shortcut.  In this PR I have done that.  On it's own this shortcut isn't very useful, but if you connect it to another intent like copy to clipboard it becomes quite useful.

### Test
1. Run the branch and then open the shortcuts app.  Create a new shortcut and look for Simplenote in the apps
2. Add Copy Content From Note.  Select a note
3. search in the shortcuts sidebar for clipboard.  Add "Copy To Clipboard
4. run the shortcut.
5. Go to another text app and paste.  Confirm that the content from your note appears.

### Review
***(Required)*** Add instructions for reviewers.  For example:
> Only one developer is required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by jleandroperez — APPROVED** [review]
Works exactly as advertised!!

:shipit:

**Review by jleandroperez — APPROVED** [review]

**Review by jleandroperez — APPROVED** [review]

**Review by jleandroperez — APPROVED** [review]
:shipit:

**Comment by jleandroperez** [comment]
Huh Github got super stuck, sorry about the noise!! 😆

**Pull request merged**
