### PR TITLE
Implements SplitItemMetrics

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're bringing back the legacy Top Insets for the Tags and Notes Lists.

Ref. #718 

cc @eshurakov (thank you!!!)
cc @SylvesterWilmott Just checking if we really really want this behavior?

### Test
1. Launch Simplenote in a Catalina or Mojave system
2. Log into your account

- [x] Verify the first Notes List row is right below the Titlebar edge (there should not be top padding!)
- [ ] Verify the app hasn't changed in Big Sur

### Release
These changes do not require release notes.

### Screenshots

Catalina Before|Catalina After
-|-
Catalina Old|Catalina New

**Delta = Top Insets at launch!**

### CODE REVIEW

**Review by SylvesterWilmott — APPROVED** [review]
Looks good! Thanks

**Review by eshurakov — APPROVED** [review]
Works awesomely in Catalina. Don't have Big Sur to check it there
:shipit:

**Comment by jleandroperez** [comment]
Thank you sir!!

**Comment by jleandroperez** [comment]
And definitely *thank you* @SylvesterWilmott for checking this one out!!

**Pull request merged**
