### PR TITLE
Implements AccountVerification Controller

### LINKED ISSUE #800: Email Verification
### Details
- [x] Simperium Support to sync current Verification State #801
- [x] New “Review You Account” screen #807
- [x] New “Verify Your Email” screen #807
- [x] Display Modal Alert on Error #807
- [x] Open `app.simplenote.com/settings` in a browser if user clicks on “Change Email” #807
- [x] Show “Review You Account” on app launch if user is not verified and verification was not requested #810
- [x] Show “Verify Your Email” on app launch if verification was requested but not completed #810
- [x] Invoke the verification endpoint when the user presses `Confirm` on the `Review` / `Verify` screens #807
- [x] Analytics #807

### Mockups
macOS_Modal (Dark)
macOS_Modal (Light)
macOS_Modal_2 (Light)
macOS_Modal_Error (Light)
macOS_Modal_Error_2 (Light)

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details
In this PR we're implementing AccountVerification Controller / Coordinator. Batteries and Unit Tests included.

Closes #800

### Test: Review Account Scenario
1. Log into an account that hasn't been verified yet

- [x] Verify the **Review your Account** UI shows up right after logging in
- [x] Verify that clicking `Change Email` opens the Settings URL in your favorite browser
- [x] Verify that clicking `Confirm` causes the Backend to send you a verification email

### Test: Verify Account Scenario
1. Relaunch the app (should log into the same account as in the previous step!!)
 
- [x] Verify that after relaunching the **Verify your Email** UI shows up
- [x] Verify that pressing `Confirm` causes the Backend to resend the verification email

### Test: Dismissal
1. Relaunch the app (same account!!)

- [x] Verify the **Verify your Email** UI shows up
- [x] Click over the link you got over mail
- [x] Verify the UI gets automatically dismissed shorly after

### Test: Verified account
1. Relaunch the app (same account you've used in all of the previous steps)

- [x] Verify no **Account Verification** UI shows up

### Test: Logout
1. Log into **another** unverified Test Account

- [x] Verify the Account Verification UI shows up
- [x] Verify that Logging Out cause the alert to get dismissed (and shortly after the main window disappears!)

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by jleandroperez** [comment]
@eshurakov ready for review!! Perhaps (for testing purposes) we could map the testing URL?

Right, we'd still need to test against the final endpoint!!

**Review by eshurakov — APPROVED** [review]
Looks good! Checked using testing url.

:shipit:

**Comment by jleandroperez** [comment]
Thank you Evgeny!!

**Comment by pachlava** [comment]
[testing] Confirm that all these scenarios work, checked on mbp16 | Big Sur 11.1 | SN 2.7

**Pull request merged**
